### ISSUE TITLE
What's different between IRNet v2 and IRNet?

### ISSUE THREAD

**Issue by zhaoyizhaoyi** [microsoft/IRNet#14]
I notice that IRNet v2 also appears on the Spider leaderboard (https://yale-lily.github.io/spider). I wonder what is the difference between IRNet v2 and IRNet. Are there any structural difference in the model architecture?

**Comment by substill** [comment]
In fact, there is only very small difference. We only fixed a minor bug, and separated the prediction of T and C in SemQL.

**Comment by zhaoyizhaoyi** [comment]
One more thing. So the current source code is of version 2, right? I am supposed to get 55.4% accuracy on the dev set as the IRNet v2 on the Spider leaderboard, right? @substill
Thanks a lot!

**Comment by JasperGuo** [comment]
This is the version 1. You can get ~53.4% exact match accuracy on the dev set.

**Comment by zhaoyizhaoyi** [comment]
OK, thanks a lot. Looking forward to your v2 code.

**Comment by mnoukhov** [comment]
Just to clarify, did you fix the minor bug in this code or will it be in V2? If it isn't here, can you just quickly say what it is. I'd be happy to write the fix into a PR
