### ISSUE TITLE
IRNet+Bert版本

### ISSUE THREAD

**Issue by 489597448** [microsoft/IRNet#17]
您好，我在原有IRNet网络上加入Bert后，sketch acc可以上升到81，但SemQL  acc降到38，您觉得是什么原因吗？是因为参数问题吗，学习率，bacth size等吗
    期待您的答复。

**Comment by JasperGuo** [comment]
您好，从您描述的情况来看，column 和 table 的 prediction 下降的幅度应该非常多。
是否可以具体地描述如何利用 bert 建模？

**Comment by 489597448** [comment]
将问句&nbsp; 列名&nbsp; 表名三部分进行拼接&nbsp; 输入bert&nbsp; 然后bert输出分别取出三部分向量，对多个词语的取平均向量表示




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JasperGuo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月18日(星期六) 中午11:16
收件人:&nbsp;"microsoft/IRNet"<IRNet@noreply.github.com&gt;;
抄送:&nbsp;"胡晓辉"<489597448@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/IRNet] IRNet+Bert版本 (#17)




您好，从您描述的情况来看，column 和 table 的 prediction 下降的幅度应该非常多。
 是否可以具体地描述如何利用 bert 建模？

**Comment by whuFSN** [comment]
问句+列名+表名拼接时（加入[SEP]），发现有一些样本的长度会大于512，请问您是怎么解决的呢，我看论文中The construction of table representations follows the same way。这个意思是用两个bert，一个是question+column,一个是question+table,还是说是一个bert，采用question+column+table的形式呢？

**Comment by 489597448** [comment]
> 问句+列名+表名拼接时（加入[SEP]），发现有一些样本的长度会大于512，请问您是怎么解决的呢，我看论文中The construction of table representations follows the same way。这个意思是用两个bert，一个是question+column,一个是question+table,还是说是一个bert，采用question+column+table的形式呢？

bert长度默认是512，所以对这部分我没有处理

**Comment by Achronferry** [comment]
> 将问句&nbsp; 列名&nbsp; 表名三部分进行拼接&nbsp; 输入bert&nbsp; 然后bert输出分别取出三部分向量，对多个词语的取平均向量表示
> …

论文里对列名和表名是过LSTM而不是取平均，我跑出来dev比给的低两个百分点。同求具体参数

**Comment by 489597448** [comment]
> > 将问句  列名  表名三部分进行拼接  输入bert  然后bert输出分别取出三部分向量，对多个词语的取平均向量表示
> > …
> 
> 论文里对列名和表名是过LSTM而不是取平均，我跑出来dev比给的低两个百分点。同求具体参数

跑出来验证集59吗

**Comment by Achronferry** [comment]
> 将问句  列名  表名三部分进行拼接  输入bert  然后bert输出分别取出三部分向量，对多个词语的取平均向量表示
> …
> 
> 论文里对列名和表名是过LSTM而不是取平均，我跑出来dev比给的低两个百分点。同求具体参数
> 
> 跑出来验证集59吗

差不多吧，semQL的acc58.几

**Comment by whuFSN** [comment]
> > 将问句  列名  表名三部分进行拼接  输入bert  然后bert输出分别取出三部分向量，对多个词语的取平均向量表示
> > …
> > 论文里对列名和表名是过LSTM而不是取平均，我跑出来dev比给的低两个百分点。同求具体参数
> > 跑出来验证集59吗
> 
> 差不多吧，semQL的acc58.几

如何处理问句+列名+表名>512的问题呢

**Comment by 489597448** [comment]
> > > 将问句  列名  表名三部分进行拼接  输入bert  然后bert输出分别取出三部分向量，对多个词语的取平均向量表示
> > > …
> > 
> > 
> > 论文里对列名和表名是过LSTM而不是取平均，我跑出来dev比给的低两个百分点。同求具体参数
> 


> > > 将问句  列名  表名三部分进行拼接  输入bert  然后bert输出分别取出三部分向量，对多个词语的取平均向量表示
> > > …
> > > 论文里对列名和表名是过LSTM而不是取平均，我跑出来dev比给的低两个百分点。同求具体参数
> > > 跑出来验证集59吗
> > 
> > 
> > 差不多吧，semQL的acc58.几
> 
> 如何处理问句+列名+表名>512的问题呢


> > > 将问句  列名  表名三部分进行拼接  输入bert  然后bert输出分别取出三部分向量，对多个词语的取平均向量表示
> > > …
> > > 论文里对列名和表名是过LSTM而不是取平均，我跑出来dev比给的低两个百分点。同求具体参数
> > > 跑出来验证集59吗
> > 
> > 
> > 差不多吧，semQL的acc58.几
> 
> 如何处理问句+列名+表名>512的问题呢

我没单独做处理，超过就截断， 你怎么处理的

**Comment by 489597448** [comment]
> > > 将问句  列名  表名三部分进行拼接  输入bert  然后bert输出分别取出三部分向量，对多个词语的取平均向量表示
> > > …
> > > 论文里对列名和表名是过LSTM而不是取平均，我跑出来dev比给的低两个百分点。同求具体参数
> > > 跑出来验证集59吗
> > 
> > 
> > 差不多吧，semQL的acc58.几
> 
> 如何处理问句+列名+表名>512的问题呢

咱加个微信详细说吧

**Comment by whuFSN** [comment]
超过就截断，怎么获取超出部分的列或者表的表征呢，那超出的列或表不是就不会被选择了吗？
