### ISSUE TITLE
It seems that the repo lacks the codes of IRNet+BERT(base)	?

### ISSUE THREAD

**Issue by jaredwei01** [microsoft/IRNet#2]
It seems that it is not a complete version of the whole paper, maybe it lacks a part of "IRNet+BERT". @JasperGuo

**Comment by project-delphi** [comment]
Yes please.

**Comment by guotong1988** [comment]
Same question.

**Comment by substill** [comment]
The Bert version will come soon. Stay tuned!

**Comment by saparina** [comment]
@substill do you have any updates?

**Comment by TapanHP1995** [comment]
@substill Any updates on this?

**Comment by sharmanirudh** [comment]
@substill any updates?
Thanks.

**Comment by JasperGuo** [comment]
Sorrt for the late replay.
We have uploaded the BERT code.
Please pull the latest version of the code and checkout the BERT branch.

**Comment by JasperGuo** [comment]
We have uploaded a trained BERT model.
https://drive.google.com/open?id=1o9cWUPcgFuEN6EHVWeyzN3JXEunUwcLM
