### ISSUE TITLE
Issue in model.forward

### ISSUE THREAD

**Issue by shubhamk16** [microsoft/IRNet#20]
Hello guys, 
when i run this model for training, i got an error " The size of tensor a (300) must match the size of tensor b (100) at non-singleton dimension 2".  
in this line of model.forward ==>  table_embedding = table_embedding + tab_ctx 
. could anyone please answer how to solve this issue ?

**Comment by YuBoDream** [comment]
Could you tell me how you solved the problem, please？

**Comment by shubhamk16** [comment]
sure @YuBoDream, just change the dimension size of the hidden_size and embed size, att_vec_size and  col_embed_size to 300.

**Comment by YuBoDream** [comment]
Thank you very much
