### ISSUE TITLE
Execute IRNET on other datasets like  wikisql,ATIS,Advising 

### ISSUE THREAD

**Issue by anshudaur** [microsoft/IRNet#35]
HI, I would like to convert other dataset to similiar SemQL format and test IRNET on other datasets as well. However since the file types are different,  Can you please suggest how i should go about it?

Thanks 
Anshu

**Comment by vcbeaut** [comment]
> HI, I would like to convert other dataset to similiar SemQL format and test IRNET on other datasets as well. However since the file types are different, Can you please suggest how i should go about it?
> 
> Thanks
> Anshu

can you solve the question? thanks
