### ISSUE TITLE
what is meant by save_fold/ output_fold

### ISSUE THREAD

**Issue by ng2dev** [microsoft/IRNet#4]
I would like to know a suggestion for an average best practice [save_fold]/[output_fold] value.
I do not really understand what is meant by this option and how to understand the print statement
     
     $ sh eval.sh 0 100
     1028 0

Much Thanks

**Comment by JasperGuo** [comment]
It will create a text file where all the predicted SQL queries are written in it.
In the example you provide, there should be a file named 100 in the project folder.
