### ISSUE TITLE
where is the file,english_RelatedTo.pkl and english_IsA.pkl of conceptNet?

### ISSUE THREAD

**Issue by xiaer1** [microsoft/IRNet#6]
I want to generate train/dev data by myself,would you please give me a link,thanks.

**Comment by panamantis** [comment]
You can start with the official ConceptNet repository [https://github.com/commonsense/conceptnet5](url).  The core setup can be installed as a 30GB module and builds itself from raw data.  You can expand what you want from there but I'll warn you that it's not trivial.

**Comment by xiaer1** [comment]
Ok.Thanks for your reply and  advice.

**Comment by JasperGuo** [comment]
Thanks @panamantis .
@xiaer1 You can download the two .pkl from this link [https://drive.google.com/file/d/1LgyjtDmf3Xd1txwq8HwKD6d6VJj5pLmn/view?usp=sharing](url).

**Comment by xiaer1** [comment]
That's great, thanks.

**Comment by anshudaur** [comment]
HI , The link isn't working. Can you please share a link providing the .pkl files?

Thanks
Anshu

**Comment by panamantis** [comment]
The link works.  Just be sure not to copy the period at the end -- or copy
and paste it manually.
